language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # - docker build -t simple-node .
  # - docker tag simple-node YOUR_DOCKER_HUB/simple-node:latest
  - docker-compose -f ./project/docker-compose-build.yaml build --parallel
  #  tagging
  # TODO: append automatically. could use a bash script to pull the image, get the tag, increment it
  - docker tag reverseproxy taofeekat28/reverseproxy:v1
  - docker tag udagram-api-user taofeekat28/udagram-api-user:v1
  - docker tag udagram-api-feed taofeekat28/udagram-api-feed:v1
  - docker tag udagram-frontend:local taofeekat28/udagram-frontend:v1


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push YOUR_DOCKER_HUB/simple-node
  - docker push taofeekat28/reverseproxy:v1
  - docker push taofeekat28/udagram-api-user:v1
  - docker push taofeekat28/udagram-api-feed:v1
  - docker push taofeekat28/udagram-frontend:v1